name: 'Setup Node'

description: 'Setup node and pnpm'

runs:
  using: 'composite'
  steps:

    - name: Install Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      shell: bash
      run: npm install --frozen-lockfile
