# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build # will run `yarn build:prod` command
        
    - name: Deploy
      # 別人的actions拿來借用
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        BRANCH: gh-pages # deploy 到 gh-pages 這個分支
        FOLDER: "dist" # build 後的資料夾
        clean: false  # do not remove other files (including whole doc versions)
        single-commit: true