# name: Dependabot post-update
name: Build detection
on:
  push:
    branches: [main]

jobs:
  post-update:
    # if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Build
        run: npm run build

      - name: Deploy
        # 別人的actions拿來借用
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }} # Settings > Secret 建立的 ACCESS_TOKEN，推同個 repo 的話可以不需要
          BRANCH: gh-pages # deploy 到 gh-pages 這個分支
          FOLDER: "./apps/web-antd/dist" # build 後的資料夾
          clean: false  # do not remove other files (including whole doc versions)
          single-commit: true