# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'pnpm'

    - run: pnpm install
    - run: pnpm run build
    
    - name: Deploy
      # 別人的actions拿來借用
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        BRANCH: gh-pages # deploy 到 gh-pages 這個分支
        FOLDER: "dist" # build 後的資料夾
        clean: false  # do not remove other files (including whole doc versions)
        single-commit: true