name: Deploy React App

permissions:
  actions: write       # Necessary to cancel workflow executions
  checks: write        # Necessary to write reports
  pull-requests: write # Necessary to comment on PRs
  contents: read
  id-token: write
  packages: write

on:
  push:
    branches:
      - main  # 触发部署的分支，可以是你需要的分支，比如 main 或 master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置Node.js版本
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # 根据项目的Node版本来调整

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # 构建React项目
      - name: Build React app
        run: npm run build

      # 部署到GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # 部署的目标分支
          folder: build  # React构建产物的目录
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub自动生成的Token，用于认证

